### PR TITLE
Add support for forks

### PR DESCRIPTION
**Pull request by mgilardi**
@jun3453 First off, thanks for creating this Action. I forked in order to add fork support (for example, when you have PRs coming from a fork into an original repo), but then thought that others could benefit from the feature so I wanted to PR back to your repo. It's up to you if you want to merge, but wanted to offer either way.

### CODE REVIEW

**Comment by jun3453** [comment]
I feel bad.
I didn't notice your pull request.
It looks good so I'll merge it!

**Comment by mgilardi** [comment]
> I feel bad.
> I didn't notice your pull request.
> It looks good so I'll merge it!

@jun3453 No problem at all! Thanks for checking it out.

**Comment by jun3453** [comment]
I just fixed the conflict.
Let's merge and check!

**Comment by jun3453** [comment]
@mgilardi
v1.2.0 has been released!
This implementation is included.
I also adjusted it here to match the implementation of #9 .

Thank you very much!

**Pull request merged**
